trainX="$1"
trainX_no_label="$2"
python3 main.py model/word2vec model/lstm128.h5 -g 0 -f build_model2 -t "$trainX" "$trainX_no_label"
python3 main.py model/word2vec model/lstm128-3.h5 -g 0 -t "$trainX" "$trainX_no_label"
python3 main_acc.py model/word2vec model/lstm128-3_acc.h5 -g 0 -t "$trainX" "$trainX_no_label"
